5-13,5-14

In [43]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler,StandardScaler
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.preprocessing import Normalizer
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.decomposition import PCA

In [34]:
d=dict([("low",0),('medium',1),('high',2)])
def map_salary(s):
    return d.get(s,0)

In [48]:
#sl:satisfaction_level--False:MinMaxScaler,True:StandardScaler
#le:last_evaluation--False:MinMaxScaler,True:StandardScaler
#npr:number_project--False:MinMaxScaler,True:StandardScaler
#amh:average_montly_hours--
#tsc:time_spend_company--
#wa:Work_accident--
#pl5:promotion_last_5years--

#dp:department--False:LabelEncoding,True:OneHotEncoding
#slr:salary--
def hr_preprocessing(sl=False,le=False,npr=False,
                     amh=False,tsc=False,wa=False,pl5=False,dp=False,slr=False,
                     lower_d=False,ld_n=1):
    df=pd.read_csv(r'C://HR.csv')
    
    #2. 清洗数据
    df=df.dropna(subset=['satisfaction_level','last_evaluation'])
    df=df[df['satisfaction_level']<=1][df['salary']!='nme']
    df=df.rename(columns={'sales':'department'})
    #1. 标注
    label=df["left"]
    df=df.drop("left",axis=1)
    #3. 特征选择
    #4. 特征处理
    scaler_lst=[sl,le,npr,amh,tsc,wa,pl5]
    column_lst=['satisfaction_level','last_evaluation','number_project',
                'average_montly_hours','time_spend_company','Work_accident','promotion_last_5years']
    for i in range(len(scaler_lst)):
        if not scaler_lst[i]:
            df[column_lst[i]]=MinMaxScaler().fit_transform(df[column_lst[i]].values.reshape(-1,1)).reshape(1,-1)[0]
        else:
            df[column_lst[i]]=StandardScaler().fit_transform(df[column_lst[i]].values.reshape(-1,1)).reshape(1,-1)[0]
            
    sacaler_lst=[slr,dp]
    column_lst=['salary','department']
    for i in range(len(scaler_lst)):
        if not scaler_lst[i]:
            if column_lst[i]=="salary":
                df[column_lst[i]]=[map_salary(s) for s in df["salary"].values]
            else:
                df[column_lst[i]]=LabelEncoder().fit_transform(df[column_lst[i]])
            df[column_lst[i]]=MinMaxScaler().fit_transform(df[column_lst[i]].values.reshape(-1,1)).reshape(1,-1)[0]
        else:
            df=pd.get_dummies(df,columns=[column_lst[i]])
    
    if lower_d:
        #return LinearDiscriminantAnalysis(n_components=ld_n)
        return PCA(n_components=ld_n).fit_transform(df.values),label
    return df,label

In [49]:
hr_preprocessing(sl=False,le=False,npr=False)

D:\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)

IndexError: list index out of range

In [18]:
def main():
    print(hr_preprocessing(sl=True,le=True))
if __name__=='__main__':
    main()

       satisfaction_level  last_evaluation  number_project  \
0               -0.936495        -1.087275               2
1                0.752814         0.840707               5
2               -2.022479         0.957554               7
3                0.431041         0.899131               5
4               -0.976716        -1.145699               2
5               -0.815830        -1.262546               2
6               -2.062701         0.314894               6
7                1.235474         0.782283               5
8                1.114809         1.658639               5
9               -0.775608        -1.087275               2
10              -0.654943        -1.028852               2
11              -2.022479         0.548588               6
12               0.913701         1.191249               4
13              -0.815830        -0.970428               2
14              -1.016938        -0.912004               2
15              -0.936495        -1.028852               2
16              -0.654943        -1.437818               2
17               0.672371         1.600215               4
18              -0.654943        -1.204123               2
19               0.591928         1.015978               5
20              -2.022479         0.665436               6
21              -0.936495        -0.970428               2
22              -2.102922         1.366520               6
23              -0.614722        -0.853580               2
24              -0.856051        -1.087275               2
25               1.114809         1.191249               5
26               0.833258         0.899131               4
27              -0.856051        -1.320970               2
28              -0.815830        -1.496241               2
29              -0.936495        -1.262546               2
...                   ...              ...             ...
14969           -0.735386        -1.496241               2
14970            0.672371         1.249673               4
14971           -0.896273        -1.554665               2
14972           -2.022479         1.483368               6
14973           -1.016938        -1.145699               2
14974           -1.016938        -1.028852               2
14975           -2.062701         0.431741               7
14976           -0.856051        -1.437818               2
14977            0.793036         0.782283               4
14978           -0.856051        -1.437818               2
14979           -2.102922         1.249673               6
14980            0.591928         1.015978               5
14981            0.471263         1.249673               5
14982           -0.936495        -1.320970               2
14983            0.431041         0.723860               5
14984           -0.856051        -0.912004               2
14985            1.195252         1.600215               5
14986            0.953923         0.782283               4
14987            1.155031        -0.094072               5
14988           -0.614722        -0.970428               2
14989           -0.735386        -0.853580               2
14990            1.114809         0.957554               5
14991           -2.102922         0.548588               6
14992           -0.856051        -1.379394               2
14993            0.591928         0.665436               6
14994           -0.856051        -0.853580               2
14995           -0.976716        -1.379394               2
14996           -0.976716        -1.087275               2
14997           -2.022479         1.424944               6
14998           -0.976716        -1.145699               2

       average_montly_hours  time_spend_company  Work_accident  \
0                       157                   3              0
1                       262                   6              0
2                       272                   4              0
3                       223                   5              0
4                       159                   3              0
5                       153                   3              0
6                       247                   4              0
7                       259                   5              0
8                       224                   5              0
9                       142                   3              0
10                      135                   3              0
11                      305                   4              0
12                      234                   5              0
13                      148                   3              0
14                      137                   3              0
15                      143                   3              0
16                      160                   3              0
17                      255                   6              0
18                      160                   3              1
19                      262                   5              0
20                      282                   4              0
21                      147                   3              0
22                      304                   4              0
23                      139                   3              0
24                      158                   3              0
25                      242                   5              0
26                      239                   5              0
27                      135                   3              0
28                      128                   3              0
29                      132                   3              0
...                     ...                 ...            ...
14969                   157                   3              0
14970                   225                   5              0
14971                   140                   3              0
14972                   310                   4              0
14973                   143                   3              0
14974                   153                   3              0
14975                   310                   4              0
14976                   136                   3              0
14977                   251                   6              0
14978                   144                   3              0
14979                   296                   4              0
14980                   238                   5              0
14981                   162                   4              0
14982                   137                   3              0
14983                   257                   5              0
14984                   148                   3              0
14985                   254                   5              0
14986                   247                   6              0
14987                   206                   4              0
14988                   145                   3              0
14989                   159                   3              1
14990                   228                   5              1
14991                   257                   4              0
14992                   155                   3              0
14993                   293                   6              0
14994                   151                   3              0
14995                   160                   3              0
14996                   143                   3              0
14997                   280                   4              0
14998                   158                   3              0

       promotion_last_5years       sales  salary
0                          0       sales     low
1                          0       sales  medium
2                          0       sales  medium
3                          0       sales     low
4                          0       sales     low
5                          0       sales     low
6                          0       sales     low
7                          0       sales     low
8                          0       sales     low
9                          0       sales     low
10                         0       sales     low
11                         0       sales     low
12                         0       sales     low
13                         0       sales     low
14                         0       sales     low
15                         0       sales     low
16                         0       sales     low
17                         0       sales     low
18                         1       sales     low
19                         0       sales     low
20                         0       sales     low
21                         0       sales     low
22                         0       sales     low
23                         0       sales     low
24                         0       sales     low
25                         0       sales     low
26                         0       sales     low
27                         0       sales     low
28                         0  accounting     low
29                         0  accounting     low
...                      ...         ...     ...
14969                      0       sales  medium
14970                      0       sales  medium
14971                      0       sales  medium
14972                      0  accounting  medium
14973                      0  accounting  medium
14974                      0  accounting  medium
14975                      0          hr  medium
14976                      0          hr  medium
14977                      0          hr  medium
14978                      0          hr  medium
14979                      0   technical  medium
14980                      0   technical    high
14981                      0   technical     low
14982                      0   technical  medium
14983                      0   technical  medium
14984                      0   technical  medium
14985                      0   technical  medium
14986                      0   technical     low
14987                      0   technical     low
14988                      0   technical     low
14989                      0   technical     low
14990                      0     support     low
14991                      0     support     low
14992                      0     support     low
14993                      0     support     low
14994                      0     support     low
14995                      0     support     low
14996                      0     support     low
14997                      0     support     low
14998                      0     support     low

[14999 rows x 9 columns]

In [37]:
df

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,sales,salary
0,0.38,0.53,2,157,3,0,1,0,sales,low
1,0.80,0.86,5,262,6,0,1,0,sales,medium
2,0.11,0.88,7,272,4,0,1,0,sales,medium
3,0.72,0.87,5,223,5,0,1,0,sales,low
4,0.37,0.52,2,159,3,0,1,0,sales,low
5,0.41,0.50,2,153,3,0,1,0,sales,low
6,0.10,0.77,6,247,4,0,1,0,sales,low
7,0.92,0.85,5,259,5,0,1,0,sales,low
8,0.89,1.00,5,224,5,0,1,0,sales,low
9,0.42,0.53,2,142,3,0,1,0,sales,low
10,0.45,0.54,2,135,3,0,1,0,sales,low
11,0.11,0.81,6,305,4,0,1,0,sales,low
12,0.84,0.92,4,234,5,0,1,0,sales,low
13,0.41,0.55,2,148,3,0,1,0,sales,low
14,0.36,0.56,2,137,3,0,1,0,sales,low
15,0.38,0.54,2,143,3,0,1,0,sales,low
16,0.45,0.47,2,160,3,0,1,0,sales,low
17,0.78,0.99,4,255,6,0,1,0,sales,low
18,0.45,0.51,2,160,3,1,1,1,sales,low
19,0.76,0.89,5,262,5,0,1,0,sales,low
20,0.11,0.83,6,282,4,0,1,0,sales,low
21,0.38,0.55,2,147,3,0,1,0,sales,low
22,0.09,0.95,6,304,4,0,1,0,sales,low
23,0.46,0.57,2,139,3,0,1,0,sales,low
24,0.40,0.53,2,158,3,0,1,0,sales,low
25,0.89,0.92,5,242,5,0,1,0,sales,low
26,0.82,0.87,4,239,5,0,1,0,sales,low
27,0.40,0.49,2,135,3,0,1,0,sales,low
28,0.41,0.46,2,128,3,0,1,0,accounting,low
29,0.38,0.50,2,132,3,0,1,0,accounting,low
...,...,...,...,...,...,...,...,...,...,...
14969,0.43,0.46,2,157,3,0,1,0,sales,medium
14970,0.78,0.93,4,225,5,0,1,0,sales,medium
14971,0.39,0.45,2,140,3,0,1,0,sales,medium
14972,0.11,0.97,6,310,4,0,1,0,accounting,medium
14973,0.36,0.52,2,143,3,0,1,0,accounting,medium
14974,0.36,0.54,2,153,3,0,1,0,accounting,medium
14975,0.10,0.79,7,310,4,0,1,0,hr,medium
14976,0.40,0.47,2,136,3,0,1,0,hr,medium
14977,0.81,0.85,4,251,6,0,1,0,hr,medium
14978,0.40,0.47,2,144,3,0,1,0,hr,medium
14979,0.09,0.93,6,296,4,0,1,0,technical,medium
14980,0.76,0.89,5,238,5,0,1,0,technical,high
14981,0.73,0.93,5,162,4,0,1,0,technical,low
14982,0.38,0.49,2,137,3,0,1,0,technical,medium
14983,0.72,0.84,5,257,5,0,1,0,technical,medium
14984,0.40,0.56,2,148,3,0,1,0,technical,medium
14985,0.91,0.99,5,254,5,0,1,0,technical,medium
14986,0.85,0.85,4,247,6,0,1,0,technical,low
14987,0.90,0.70,5,206,4,0,1,0,technical,low
14988,0.46,0.55,2,145,3,0,1,0,technical,low
14989,0.43,0.57,2,159,3,1,1,0,technical,low
14990,0.89,0.88,5,228,5,1,1,0,support,low
14991,0.09,0.81,6,257,4,0,1,0,support,low
14992,0.40,0.48,2,155,3,0,1,0,support,low
14993,0.76,0.83,6,293,6,0,1,0,support,low
14994,0.40,0.57,2,151,3,0,1,0,support,low
14995,0.37,0.48,2,160,3,0,1,0,support,low
14996,0.37,0.53,2,143,3,0,1,0,support,low
14997,0.11,0.96,6,280,4,0,1,0,support,low
14998,0.37,0.52,2,158,3,0,1,0,support,low